# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_delete_loginreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
