# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_delete_loginreg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registable',
            new_name='User',
        ),
    ]
